### ISSUE TITLE
Android - Display IBAN

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-card-android#55]
As a <ins>SORA Card owner</ins> I want to <ins>see my account IBAN</ins> so that <ins>I can share it to receive money on it</ins>.

**IBAN Card**
**Design**: https://www.figma.com/file/XhTyv6TrsoVXRDlO7Ud9mS/%F0%9F%94%A8-SORA-Wallet-(in-Development)?type=design&node-id=1872-10297&mode=design&t=T0MFEg0U4SNF13CE-0

**Comment by ra9mls** [comment]
@AmadeyKuspakov when user kills the app, he doesn’t see IBAN. 
When he relogins with the phone number, he sees IBAN.
Need to fix it.

**Comment by AmadeyKuspakov** [comment]
@ra9mls got you, this issue is connected to expiration dates of access tokens: if an access token is expired, user needs to refresh it from the code of sora card lib (relogin from sora card lib), the only way I know, how to overcome this, is to do some major refactorring of architecture in sora card lib

May be @arvifox knows how to quickly fix this?
